language: cpp

# clang is not supported for poppler
compiler: gcc

os: linux

addons:
  apt:
    packages:
    - cmake
    - libboost1.55-all-dev
    - libcppunit-dev
    - dvipng
    - texlive
    - liboverlay-scrollbar-0.2-dev
    - liblcms2-dev
    - libopenjpeg-dev
    - libjpeg-dev
    - fontconfig
    - librsvg2-dev
    - glade-gtk2
#    - libpoppler-dev
#    - libpoppler-cpp-dev
#    - libpoppler-glib-dev
    sources:
    - boost-latest
    - kalakris-cmake

before_install:
  - "sudo apt-get install -y libglade2-dev"

before_script:
  - "mkdir build"
  - "cd build"

script:
  - "cmake .. -DBUILD_POPPLER=ON -DEXT_GLIBMM=ON -DCMAKE_DEBUG_INCLUDES_LDFLAGS=ON -DENABLE_MATHTEX=ON -DENABLE_OS=ON -DENABLE_CPPUNIT=ON -DUNSTABLE_LAYERS_SIDEBAR=ON -DDEBUG_COMPILE=ON"
  - "make"
  - "ctest"
