# Template for setting up an MSYS2 environment and building Xournal++ on Windows

parameters:
  build_type: ''
  cmake_flags: ''

steps:
  - script: |
      C:\msys64\usr\bin\bash -lc "mkdir build"
    env:
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      CHERE_INVOKING: yes
    displayName: 'Create build directory'
  - script: |
      C:\msys64\usr\bin\bash -lc "cmake -GNinja .. -DCMAKE_BUILD_TYPE=${{ parameters.build_type}} ${{ parameters.cmake_flags }}"
      rem Make sure pot is up to date with sources (maybe translation pipeline is currently running)
      C:\msys64\usr\bin\bash -lc "cmake --build . --target pot"
      C:\msys64\usr\bin\bash -lc "cmake --build . --target translations"
      rem Build Xournal++
      C:\msys64\usr\bin\bash -lc "cmake --build ."
    workingDirectory: ./build
    env:
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      CHERE_INVOKING: yes
    displayName: 'Build Xournal++'
