# Template for setting up the Ubuntu build environment and building Xournal++ on
# Ubuntu

parameters:
  build_type: 'Debug'
  cmake_flags: ''
  cmake_commands: ''

steps:
  - bash: |
      sudo apt-get update
      sudo apt-get install -y cmake ninja-build libcppunit-dev libgtk-3-dev libpoppler-glib-dev portaudio19-dev libsndfile-dev liblua5.3-dev libzip-dev
    displayName: 'Install dependencies'
